- name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Linting
      run: |
        # --exit-zero makes the build pass even if there are small "Style" warnings
        # but --select=E9,F63,F7,F82 still fails if there is a CRITICAL logic error
        python -m flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        python -m flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
        
    - name: Run Security Scan (Bonus for VP Role)
      run: |
        pip install bandit
        python -m bandit -r . -x ./tests
